#if defined _origin_items_const_included
  #endinput
#endif
#define _origin_items_const_included

/* Item ID constants */
#define ORIGIN_INVALID_ITEM -1

/* Item selection constants */
#define ORIGIN_ITEM_AVAILABLE 0
#define ORIGIN_ITEM_NOT_AVAILABLE 1
#define ORIGIN_ITEM_DONT_SHOW 2

/* Item types constants */
#define ORIGIN_TYPE_INVALID		3
#define ORIGIN_TYPE_PRIMARY		4
#define ORIGIN_TYPE_SECONDARY	5
#define ORIGIN_TYPE_NADE			6