#if defined _origin_zclass_const_inc
  #endinput
#endif
#define _origin_zclass_const_inc

/* Zombie Class ID constants */
#define ORIGIN_INVALID_ZOMBIE_CLASS -1

/* Class selection constants */
#define ORIGIN_CLASS_AVAILABLE 0
#define ORIGIN_CLASS_NOT_AVAILABLE 1
#define ORIGIN_CLASS_DONT_SHOW 2


#define KEY_SOUND_HEAL			1
#define KEY_SOUND_EVOLUTION		2
#define KEY_SOUND_DEATH1		3
#define KEY_SOUND_DEATH2		4
#define KEY_SOUND_HURT1			5
#define KEY_SOUND_HURT2			6
#define KEY_SOUND_INFECTED		7
#define KEY_SOUND_MAX			8

#define ORIGIN_ABILITY_ACTIVATED	8
#define ORIGIN_ABILITY_ERROR		9